# Generated by Django 6.1.1 on 2026-10-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_distance_miles',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_driving_hours',
            field=models.FloatField(default=0),
        ),
    ]
